apiVersion: apps/v1
kind: Deployment
metadata:
  name: restql-http
spec:
  selector:
    matchLabels:
      app: restql-http
  template:
    metadata:
      labels:
        app: restql-http
    spec:
      containers:
      - name: restql
        image: restql/restql-http:latest
        env:
        - name: my_service
          value: "http://my-service-endpoint/"